export default {
  CREATE_KANJI: "CREATE_KANJI",
  UPDATE_KANJI: "UPDATE_KANJI",
  DELETE_KANJI: "DELETE_KANJI",
  LOAD_KANJIS: "LOAD_KANJIS",
  FILTER_KANJIS: "FILTER_KANJIS",
  CREATE_VERB: "CREATE_VERB",
  UPDATE_VERB: "UPDATE_VERB",
  DELETE_VERB: "DELETE_VERB",
  LOAD_VERBS: "LOAD_VERBS",
  FILTER_VERBS: "FILTER_VERBS",
};
